In [3]:
import pandas as pd
import numpy as np

In [5]:
foodrating = pd.read_csv("MyFoodRatings.csv")

In [6]:
foodrating

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        4       4       4         0            0     0      0      0   
2     C        3       3       3         0            0     0      0      0   
3     D        2       2       2         0            0     0      0      0   
4     E        0       0       0         2            2     2      0      0   
5     F        0       0       0         1            1     1      0      0   
6     G        0       0       0         5            3     4      0      0   
7     H        0       0       0         4            4     4      0      0   
8     I        0       0       0         0            0     0      2      2   
9     J        0       0       0         0            0     0      1      1   
10    K        0       0       0         0            0     0      3      4   
11    L        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [8]:
foodrating = foodrating.drop('Name',axis=1)

In [18]:
U, s, VT = np.linalg.svd(foodrating, full_matrices=True)

In [19]:
U.shape

(12, 12)

In [20]:
s.shape

(9,)

In [21]:
VT.shape

(9, 9)

In [27]:
U

array([[-6.80413817e-01,  0.00000000e+00,  0.00000000e+00,
         2.58908743e-33,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.83951720e-01, -2.63148402e-01,
         1.45752665e-18,  0.00000000e+00,  0.00000000e+00],
       [-5.44331054e-01,  4.96506831e-17,  3.85856584e-18,
        -1.78352620e-17,  2.48253415e-16,  8.15015983e-17,
        -4.42281885e-01, -2.92767967e-01,  6.46521942e-01,
        -1.62440512e-02,  5.53840102e-02, -3.24881025e-02],
       [-4.08248290e-01,  4.38559108e-33,  3.19773868e-34,
        -7.06645285e-34,  1.21871670e-32,  3.18417792e-33,
        -4.79822791e-17, -6.51972922e-01, -6.38955900e-01,
        -1.00346663e-18,  4.00753524e-18, -1.59750734e-18],
       [-2.72165527e-01, -9.93013661e-17, -7.71713167e-18,
         3.56705241e-17, -4.96506831e-16, -1.63003197e-16,
         8.84563769e-01, -1.46383983e-01,  3.23260971e-01,
         3.24881025e-02, -1.10768020e-01,  6.49762050e-02],
       [ 0.00000000e+00, -3.26217015e-01, -5.1838711

In [26]:
np.diag(s[:3])

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        , 10.57703788,  0.        ],
       [ 0.        ,  0.        ,  8.84826058]])

In [28]:
VTdf = pd.DataFrame(VT)

In [31]:
VTdf[0:3]

0        1        2         3         4         5         6  \
0 -0.57735 -0.57735 -0.57735  0.000000  0.000000  0.000000  0.000000   
1  0.00000  0.00000  0.00000 -0.637875 -0.512261 -0.575068  0.000000   
2  0.00000  0.00000  0.00000  0.000000  0.000000  0.000000 -0.476163   

          7         8  
0  0.000000  0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933

In [33]:
allfoodsamerating = pd.read_csv("FoodRatings_all_same_5.csv")

In [35]:
allfoodsamerating = allfoodsamerating.drop('Name',axis=1)

In [36]:
allfoodsamerating

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         5       5       5         0            0     0      0      0   
2         5       5       5         0            0     0      0      0   
3         5       5       5         0            0     0      0      0   
4         0       0       0         5            5     5      0      0   
5         0       0       0         5            5     5      0      0   
6         0       0       0         5            5     5      0      0   
7         0       0       0         5            5     5      0      0   
8         0       0       0         0            0     0      5      5   
9         0       0       0         0            0     0      5      5   
10        0       0       0         0            0     0      5      5   
11        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [37]:
U, s, VT = np.linalg.svd(allfoodsamerating, full_matrices=True)

In [38]:
np.diag(s[:3])

array([[17.32050808,  0.        ,  0.        ],
       [ 0.        , 17.32050808,  0.        ],
       [ 0.        ,  0.        , 17.32050808]])

In [39]:
allfoodsamerating345 = pd.read_csv("FoodRatings_all_same_5_4_3.csv")

In [40]:
allfoodsamerating345 = allfoodsamerating345.drop('Name',axis=1)

In [41]:
U, s, VT = np.linalg.svd(allfoodsamerating345, full_matrices=True)

In [42]:
np.diag(s[:3])

array([[17.32050808,  0.        ,  0.        ],
       [ 0.        , 13.85640646,  0.        ],
       [ 0.        ,  0.        , 10.39230485]])