In [4]:
list_1 = [1,2,3] 
list_2 = [4,5,6]
list_3 = [7,8,9]
final_list = [list_1,list_2,list_3]
import numpy as np
array_1 = np.array([list_1,list_2,list_3])
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
import numpy as np
arr = np.array([[0,1],[1,0]])
arr1 = np.tile(arr,(4//2,4//2))
print(arr1)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [38]:
# Read the input list
input_list = [[11, 12, 13, 14],[21, 22, 23, 24],[31, 32, 33, 34]]

import numpy as np

# Convert the input list to a NumPy array
array_2d =np.array(input_list)
# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
col_first = array_2d[:,0]
row_first = array_2d[0]
col_last = array_2d[:,-1]
row_last = array_2d[-1,:]

print(col_first)
print(row_first)
print(col_last)
print(row_last)


[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]
